from pydantic import BaseModel, Field   

class DefaultTools(BaseModel, strict=True):
    editor: str = Field("nvim", description="Editor to use")
    repl: str = Field("ipython", description="REPL to use")
    browser: str = Field("firefox", description="Browser to use")
    terminal: str = Field("alacritty", description="Terminal to use")
    file_manager: str = Field("ranger", description="File manager to use")
    shell: str = Field("bash", description="Shell to use")
    pdf_viewer: str = Field("zathura", description="PDF viewer to use")
    image_viewer: str = Field("sxiv", description="Image viewer to use")
    video_player: str = Field("mpv", description="Video player to use")
    music_player: str = Field("mpd", description="Music player to use")
    rss_reader: str = Field("newsboat", description="RSS reader to use")
    email_client: str = Field("neomutt", description="Email client to use")
    password_manager: str = Field("pass", description="Password manager to use")
    note_taker: str = Field("nvim", description="Note taker to use")
    calendar: str = Field("calcurse", description="Calendar to use")
    calculator: str = Field("bc", description="Calculator to use")
    dictionary: str = Field("dict", description="Dictionary to use")
    translator: str = Field("translate-shell", description="Translator to use")
    news: str = Field("newsboat", description="News reader to use")
    weather: str = Field("wttr", description="Weather to use")
    clock: str = Field("tty-clock", description="Clock to use")
    timer: str = Field("timer", description="Timer to use")
    stopwatch: str = Field("stopwatch", description="Stopwatch to use")
    countdown: str = Field("countdown", description="Countdown to use")
    alarm: str = Field("alarm", description="Alarm to use")
    timer: str = Field("timer", description="Timer to use")
    stopwatch: str = Field("stopwatch", description="Stopwatch to use")
    countdown: str = Field("countdown", description="Countdown to use")
    alarm: str = Field("alarm", description="Alarm to use")
    timer: str = Field("timer", description="Timer to use")
